# Generated by Django 3.2.4 on 2021-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='numeroContacto',
            field=models.IntegerField(verbose_name='Numero de contacto'),
        ),
    ]
