# Generated by Django 3.2.4 on 2021-07-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mascota_numerocontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especieMascota',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Especie de la mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='razaMascota',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Raza de la mascota'),
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idFicha', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la ficha')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
            ],
        ),
    ]
