# Generated by Django 3.2.4 on 2021-07-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('idDueño', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del dueño')),
                ('nombreDueño', models.CharField(max_length=50, verbose_name='Nombre del dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la mascota')),
                ('nombreMascota', models.CharField(max_length=20, verbose_name='Nombre de la mascota')),
                ('numeroContacto', models.IntegerField(max_length=11, verbose_name='Numero de contacto')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dueño')),
            ],
        ),
    ]
